#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := Interrupciones_Semaforo_Cola_Blink

include $(IDF_PATH)/make/project.mk

